# Generated by Django 5.2 on 2025-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_profile_address_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
