# Generated by Django 5.2 on 2025-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_animal_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
