# Generated by Django 5.2 on 2025-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_animal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(max_length=255,default='Unknown Location'),
        ),
    ]
