# Generated by Django 5.2 on 2025-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0007_animal_latitude_animal_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
